#!/usr/bin/env python3
"""Builds docs/audit/SPEC_SWEEP.md from docs/audit/sweep_parts/*.md.

Each part holds one spec's requirement table (last column = status); the
matching *.fixes.md holds the Phase-2 work list for its non-DONE rows.
Counts are taken from the tables, not from the parts' counts comments.
Usage: python3 scripts/assemble_spec_sweep.py
"""
import os, re, sys, collections

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PARTS = os.path.join(ROOT, "docs", "audit", "sweep_parts")
OUT = os.path.join(ROOT, "docs", "audit", "SPEC_SWEEP.md")
STATUSES = ["DONE", "NO-GUI", "NO-TEST", "PARTIAL", "MISSING", "OWNED", "DEFERRED"]

def spec_names():
    names = sorted(f[:-3] for f in os.listdir(os.path.join(ROOT, "spec")) if f.endswith(".md"))
    names += ["proposals-visual-polish"]
    docs = sorted(f[:-3] for f in os.listdir(PARTS) if f.startswith("docs-") and not f.endswith(".fixes.md"))
    return names, docs

def count(text):
    c = collections.Counter()
    for line in text.splitlines():
        if not line.startswith("|") or line.startswith("|---") or line.startswith("| Req"):
            continue
        cells = [x.strip() for x in line.strip().strip("|").split("|")]
        st = cells[-1].strip("* ").upper()
        for s in STATUSES:
            if st.startswith(s):
                c[s] += 1
                break
    return c

def main():
    specs, docs = spec_names()
    rows, body, missing = [], [], []
    total = collections.Counter()
    for name in specs + docs:
        p = os.path.join(PARTS, name + ".md")
        if not os.path.exists(p):
            missing.append(name)
            continue
        text = open(p, encoding="utf-8").read().strip()
        text = re.sub(r"<!-- counts.*?-->", "", text).strip()
        c = count(text)
        total += c
        n = sum(c.values())
        rows.append("| [%s](#%s) | %s | %d | %s |" % (
            name, re.sub(r"[^a-z0-9_-]", "", (name + "md").lower()),
            " | ".join(str(c[s]) for s in STATUSES), n,
            "%d%%" % round(100 * c["DONE"] / n) if n else "-"))
        body.append(text)
        fx = os.path.join(PARTS, name + ".fixes.md")
        if os.path.exists(fx):
            ft = open(fx, encoding="utf-8").read().strip()
            if ft:
                body.append("<details><summary>Work list (" + name + ")</summary>\n\n" + ft + "\n\n</details>")
    n = sum(total.values())
    head = ["# SPEC-SWEEP: every spec file against the code", "",
            "Branch `claude/luthier-spec-sweep`. One section per spec file (and per repo doc that",
            "states features); each row is one actionable requirement. Status: DONE (implemented,",
            "reachable in the GUI where a control is needed, tested), NO-GUI, NO-TEST, PARTIAL,",
            "MISSING, OWNED (built by an active workstream, see its branch), DEFERRED (reason given).",
            "Generated by `scripts/assemble_spec_sweep.py` from `docs/audit/sweep_parts/`;",
            "decisions and the fix log are in `docs/coverage/SPEC-SWEEP.md`.", "",
            "## Summary", "",
            "| Spec | " + " | ".join(STATUSES) + " | Rows | % done |",
            "|---|" + "---|" * (len(STATUSES) + 2)]
    head += rows
    head.append("| **Total** | " + " | ".join("**%d**" % total[s] for s in STATUSES) + " | **%d** | **%d%%** |" % (n, round(100 * total["DONE"] / max(n, 1))))
    if missing:
        head += ["", "Not yet audited: " + ", ".join(missing)]
    open(OUT, "w", encoding="utf-8", newline="\n").write("\n".join(head) + "\n\n" + "\n\n".join(body) + "\n")
    print("wrote", OUT, "rows", n, dict(total), "missing", missing)

if __name__ == "__main__":
    main()
