#!/usr/bin/env python3
"""Builds docs/audit/REMAINING.md from the PARTIAL/MISSING rows in docs/audit/sweep_parts/*.md.

Impact tags (CRASH / FEATURE / POLISH / DOCS) come from docs/audit/remaining_impact.tsv
(spec, req, status, area, impact, one-line); rows without a tag default to FEATURE.
Usage: python3 scripts/build_remaining.py
"""
import os, collections
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PARTS = os.path.join(ROOT, "docs", "audit", "sweep_parts")
TAGS = os.path.join(ROOT, "docs", "audit", "remaining_impact.tsv")
OUT = os.path.join(ROOT, "docs", "audit", "REMAINING.md")
TIERS = [("CRASH", "1. Crash / data loss / audio-thread hazard / state corruption"),
         ("FEATURE", "2. User-visible feature gap"), ("POLISH", "3. Polish (visual, UX, tuning)"),
         ("DOCS", "4. Docs / tests / process")]

def main():
    tags = {}
    for l in open(TAGS, encoding="utf-8"):
        c = l.rstrip("\n").split("\t")
        if len(c) >= 6:
            tags[(c[0], c[1])] = c
    rows, untagged = [], 0
    for f in sorted(os.listdir(PARTS)):
        if not f.endswith(".md") or f.endswith(".fixes.md"):
            continue
        spec = f[:-3]
        for l in open(os.path.join(PARTS, f), encoding="utf-8"):
            if not l.startswith("|") or l.startswith("|---") or l.startswith("| Req"):
                continue
            cells = [x.strip() for x in l.strip().strip("|").split("|")]
            st = cells[-1].strip("* ").upper()
            for s in ("PARTIAL", "MISSING"):
                if st.startswith(s):
                    t = tags.get((spec, cells[0].split()[0]))
                    if t is None:
                        untagged += 1
                        t = [spec, cells[0].split()[0], s, "General", "FEATURE", cells[1] if len(cells) > 1 else ""]
                    rows.append((spec, cells[0].split()[0], s, t[3], t[4] if t[4] in dict(TIERS) else "FEATURE", t[5]))
    out = ["# Remaining work: every still-MISSING / PARTIAL row", "",
           "Generated by `scripts/build_remaining.py` from `docs/audit/sweep_parts/` (status) and",
           "`docs/audit/remaining_impact.tsv` (impact tag and one-line gap). Ranked by ship impact,",
           "grouped by area within each tier; one line per row: `spec REQ [status]: gap`.", "",
           "Totals: %d rows (%d MISSING, %d PARTIAL). By tier: %s." % (
               len(rows), sum(r[2] == "MISSING" for r in rows), sum(r[2] == "PARTIAL" for r in rows),
               ", ".join("%s %d" % (k, sum(r[4] == k for r in rows)) for k, _ in TIERS)), ""]
    for key, title in TIERS:
        sel = [r for r in rows if r[4] == key]
        out += ["## " + title + " (%d)" % len(sel), ""]
        by = collections.defaultdict(list)
        for r in sel:
            by[r[3]].append(r)
        for area in sorted(by, key=lambda a: (-len(by[a]), a)):
            out += ["### " + area + " (%d)" % len(by[area]), ""]
            for r in by[area]:
                out.append("- %s %s [%s]: %s" % (r[0], r[1], r[2], r[5]))
            out.append("")
    open(OUT, "w", encoding="utf-8", newline="\n").write("\n".join(out))
    print("wrote", OUT, len(rows), "rows,", untagged, "untagged")

if __name__ == "__main__":
    main()
