set(LUTHIER_EDITION "PAID" CACHE STRING "Which Luthier edition to build: PAID or FREE")
set_property(CACHE LUTHIER_EDITION PROPERTY STRINGS PAID FREE)
string(TOUPPER "${LUTHIER_EDITION}" LUTHIER_EDITION)

if (LUTHIER_EDITION STREQUAL "PAID")
    set(LUTHIER_IS_PRO 1)
    set(LUTHIER_PRODUCT_NAME "Luthier Pro")
    set(LUTHIER_PLUGIN_CODE Lthr)
    set(LUTHIER_BUNDLE_ID "com.luthieraudio.luthier")
    set(LUTHIER_CLAP_ID "com.luthieraudio.luthier")
    set(LUTHIER_CONTENT_FOLDER "Luthier")
elseif (LUTHIER_EDITION STREQUAL "FREE")
    set(LUTHIER_IS_PRO 0)
    set(LUTHIER_PRODUCT_NAME "Luthier Free")
    set(LUTHIER_PLUGIN_CODE Lthf)
    set(LUTHIER_BUNDLE_ID "com.luthieraudio.luthierfree")
    set(LUTHIER_CLAP_ID "com.luthieraudio.luthier-free")
    set(LUTHIER_CONTENT_FOLDER "Luthier Free")
else()
    message(FATAL_ERROR "LUTHIER_EDITION must be PAID or FREE (got '${LUTHIER_EDITION}')")
endif()

message(STATUS "Luthier edition: ${LUTHIER_EDITION} (${LUTHIER_PRODUCT_NAME})")
