#pragma once

/*  The guitar illustration (guitar-illustration.md).

    Draws the parts guitar that is playing - a WorkshopGuitar - procedurally,
    from its parts: the body outline from the body style, the neck and
    headstock from the neck part, bridge, tailpiece, pickups, pickguard,
    strings and finish from theirs (ground rules 1 and 3).

    Coordinates are millimetres (section 1): origin at the centre of the
    bridge saddle, X positive toward the headstock, Y positive toward the
    treble side. On screen the headstock is on the left and the bass strings
    at the top, which is how a right-handed player sees the guitar on their
    knee; fitTransform() maps the scene into any rectangle that way.

    The static scene (section 2.1) is built once per guitar and cached by the
    caller under `key`; live overlays (2.2) are painted over it each frame and
    never invalidate it.

    Body and headstock outlines are data (BodyOutlines.h, generated by
    Tools/body_outlines.py), so a new shape is a table entry, and a part's
    `illustration` block can override them (section 18).

    Materials (proposals/visual-polish.md 1, approved): one key light from the
    top left, baked into the scene as extra shapes flagged `lit` - diffuse
    falloff, lacquer sheen, metal reflections and short drop shadows. The
    High-contrast palette builds without them (visual-polish 0.2).
*/

#include <juce_gui_basics/juce_gui_basics.h>
#include "../../Model/Workshop/PartLibrary.h"

#include <array>
#include <vector>

namespace luthier
{

//==============================================================================
/** The parts the illustration hit-tests (section 13.1). */
enum class GuitarRegion
{
    none = 0,
    body, pickguard, soundhole, bridge, tailpiece,
    pickupNeck, pickupMiddle, pickupBridge,
    strings, neck, fretboard, nut, headstock, tuners,
    controls, selector, jack,
    pick, slideBar, capo,        ///< the player's accessories, overlays on the bench (workshop-ui.md 4)
    numRegions
};

const char* getGuitarRegionName (GuitarRegion) noexcept;

//==============================================================================
struct GuitarScene
{
    /** One filled / stroked shape of the static scene, in paint order. */
    struct Shape
    {
        juce::Path path;
        juce::FillType fill { juce::Colours::transparentBlack };     ///< transparent to skip the fill
        juce::FillType stroke { juce::Colours::transparentBlack };   ///< transparent to skip the stroke
        float strokeMm = 0.0f;
        bool strokeIsHairline = false;        ///< stroke at a fixed 1 px, whatever the zoom
        int clip = -1;                        ///< index into `clips`, or -1
        bool lit = false;                     ///< a lighting layer: omitted from flat renders
    };

    /** A string, drawn per material (section 10) from its anchor to its tuner. */
    struct StringLine
    {
        juce::Point<float> tail, saddle, nut, post;
        juce::Colour colour, winding;
        float widthMm = 0.3f;
        float minWidthPx = 1.0f;              ///< section 10's line width, the floor at small zooms
        bool wound = false, dashedWinding = false;
        int index = 0;                        ///< the engine's string index: 0 = the high E (engine.md 1)
    };

    /** A clickable part (section 13.1): the topmost region containing a point wins. */
    struct Hit
    {
        GuitarRegion region = GuitarRegion::none;
        juce::Path area;
        juce::String description;             ///< section 16's accessible text
    };

    juce::String family = "electric", bodyStyle, headstockStyle;
    int numStrings = 6;
    double scaleMm = 648.0;

    std::vector<juce::Path> clips;
    std::vector<Shape> shapes;                ///< body, finish, pickguard, holes, hardware, neck, frets, headstock
    std::vector<StringLine> strings;          ///< painted over `shapes`
    std::vector<Shape> overStrings;           ///< tuner posts and string trees, over the strings
    std::vector<Hit> hits;                    ///< in z-order, back to front

    /** Section 16, per string (engine index): "String 6: ... wound, 46 gauge." */
    std::vector<juce::String> stringDescriptions;

    /** Per string (engine index), where it leaves the saddle and reaches the nut. */
    std::vector<juce::Point<float>> saddlePoints, nutPoints;
    int numFrets = 22;

    /** A point on a string at a fret position (0 = the nut; 3.5 = between frets 3 and 4). */
    juce::Point<float> stringAt (int stringIndex, float fret) const noexcept;

    /** Where a played note shows: midway between the fret and the one below it. */
    juce::Point<float> noteAt (int stringIndex, int fret) const noexcept;

    /** The pickups' outlines, neck / middle / bridge; empty if not fitted. */
    std::array<juce::Path, 3> pickupAreas {};

    /** The control knobs in the body style's order (volumes first, then tones). */
    std::vector<juce::Point<float>> knobCentres;
    float knobRadiusMm = 9.0f;

    juce::Rectangle<float> bounds;            ///< everything, mm
    juce::int64 key = 0;                      ///< section 2.1's cache key
};

//==============================================================================
/** What is sounding now (section 2.2): painted over the cached scene. */
struct GuitarOverlay
{
    std::array<float, 12> stringLevel {};     ///< 0..1 per string (engine index)
    std::array<float, 12> stringFret {};      ///< fretted position, <= 0 = open / unknown
    float slideFret = -1.0f;                  ///< slide bar position, -1 = off
    int highlightedPickup = -1;               ///< hover (0 neck, 1 middle, 2 bridge)
    GuitarRegion hovered = GuitarRegion::none;
    GuitarRegion selected = GuitarRegion::none;
    juce::Colour accent { 0xffd4a24c };
    bool reducedMotion = false;

    // Layers 28-29 and the capo (gui-integration.md 21, workshop-ui.md 2).
    float slideSlantDeg = 0.0f;
    juce::Colour slideColour { 0xffcfe3e8 };   ///< the bar's material (slide-guitar.md 2.1)
    int capoFret = 0;                          ///< 0 = no capo
    juce::uint32 capoMask = 0xffffffffu;       ///< a partial capo's strings (engine index)
    float pickPositionMm = -1.0f;              ///< from the saddle; < 0 = no pick drawn
    float pickAngleDeg = 0.0f;
    float pickSizeMm = 30.0f;                  ///< drawn at true relative size
    bool handles = false;                      ///< the bench's 8 px accent drag handles

    // Section 19's played-note dots (IllustrationMotion.h), when a caller times them.
    bool useDots = false;
    std::array<float, 12> dotAlpha {}, dotFret {};

    // Section 16: parts a reduced-motion change outlines instead of fading.
    std::array<bool, (size_t) GuitarRegion::numRegions> changed {};
    juce::Colour changedColour { 0xff6fa58a };
};

//==============================================================================
class GuitarRenderer
{
public:
    struct Options
    {
        bool materials = true;     ///< visual-polish.md 1's lighting; false for High contrast
        bool thumbnail = false;    ///< section 15's reduced detail
    };

    /** Builds the static scene for a guitar. Message thread or worker. */
    static GuitarScene build (const WorkshopGuitar& guitar, Options options);
    static GuitarScene build (const WorkshopGuitar& guitar) { return build (guitar, Options {}); }

    /** The cache key for a guitar (section 2.1): a hash of its canonical serialisation. */
    static juce::int64 keyFor (const WorkshopGuitar& guitar, Options options);

    /** Maps the scene's millimetres into `area`, headstock left, bass up. */
    static juce::AffineTransform fitTransform (const GuitarScene& scene, juce::Rectangle<float> area);

    /** Paints the static scene. */
    static void paint (juce::Graphics& g, const GuitarScene& scene, const juce::AffineTransform& mmToPx);

    /** Paints the live overlay (section 2.2) over an already painted scene. */
    static void paintOverlay (juce::Graphics& g, const GuitarScene& scene,
                              const juce::AffineTransform& mmToPx, const GuitarOverlay& overlay);

    //==========================================================================
    // The accessories' outlines in millimetres, shared by paintOverlay and the
    // bench's hit test so what is drawn is what is clicked.

    /** The capo across the strings just behind `fret` (only the masked strings for a partial one). */
    static juce::Path capoPath (const GuitarScene& scene, int fret, juce::uint32 mask = 0xffffffffu);

    /** The slide bar across every string at `fret`, rotated by `slantDeg` about its centre. */
    static juce::Path slidePath (const GuitarScene& scene, float fret, float slantDeg);

    /** A standard pick, `sizeMm` tall, over the strings `positionMm` from the saddle, turned by `angleDeg`. */
    static juce::Path pickPath (const GuitarScene& scene, float positionMm, float angleDeg, float sizeMm);

    /** The pick's rotate handle (its corner), mm. */
    static juce::Point<float> pickHandle (const GuitarScene& scene, float positionMm, float angleDeg, float sizeMm);

    /** The slide's rotate handle (its bass end), mm. */
    static juce::Point<float> slideHandle (const GuitarScene& scene, float fret, float slantDeg);

    /** The topmost region under a point given in millimetres (section 13.1). */
    static const GuitarScene::Hit* hitTest (const GuitarScene& scene, juce::Point<float> mm);

    /** Renders a guitar to an image, fitted with a margin: thumbnails and tests. */
    static juce::Image render (const WorkshopGuitar& guitar, int width, int height,
                               juce::Colour background,
                               Options options);
    static juce::Image render (const WorkshopGuitar& guitar, int width, int height,
                               juce::Colour background = juce::Colours::transparentBlack)
    {
        return render (guitar, width, height, background, Options {});
    }

    //==========================================================================
    // Section 10 and 11 tables, public so the tests can hold the renderer to them.
    static juce::Colour stringColour (const juce::String& windingMaterial, bool wound, bool bass,
                                      bool flatwound = false);
    static juce::Colour hardwareColour (const juce::String& name);
    static juce::Colour woodColour (const juce::String& wood);
};

} // namespace luthier
