#pragma once
// Generated by Tools/body_outlines.py - do not edit by hand.

/*  Headstock outlines (guitar-illustration.md 6), as data.

    Coordinates per headstock, in millimetres:
      a  from the nut toward the tip (a >= 0);
      b  lateral, NEGATIVE = bass side (the top of the screen), positive = treble.
    Drawn for a 43 mm nut (38 mm on basses): the renderer rescales b near the
    nut to the guitar's real nut width.

    `outline` is closed, from the nut's treble corner round the tip to the nut's
    bass corner, smoothed with the same centripetal Catmull-Rom as the bodies
    (a `corner` point keeps straight tangents; both nut corners are corners, so
    the nut edge is straight). `posts` and `buttons` are in string order with
    index 0 the LOWEST string; the renderer maps them onto the engine's order
    (string 0 = high E). twelve_66 pairs its posts by course: 2k and 2k + 1 are
    course k, lowest course first. Slotted headstocks: posts are the roller
    centres, buttons the keys out the sides. Headless: posts are the string
    anchors and there are no buttons.

    In-line Fender-style headstocks use a straight string pull: the post line
    slants toward the treble side so every string runs almost straight from its
    nut slot to its post (the high-E post sits on the treble side of centre).
*/

#include <cstring>

namespace luthier::outlines
{

struct HeadPt { float a, b; bool corner = false; };

enum class HeadLayout { inline6, inlineReverse, threeThree, twoTwo, threeOne, fourInline, slotted, sixSix, headless };

struct HeadstockStyle
{
    const char* id;
    HeadLayout layout;
    const HeadPt* outline; int numOutline;
    const HeadPt* posts; int numPosts;
    const HeadPt* buttons; int numButtons;
    float buttonLengthMm, buttonWidthMm;
    const HeadPt* trussCover; int numTrussCover;
    const HeadPt* slots[2]; int numSlot[2];
    HeadPt stringTree; bool hasStringTree;
};

//==============================================================================
namespace headstock_data
{
    // strat_inline6
    //   Straight bass edge slanting ~17 deg toward the treble side, so each string runs almost
    //   straight to its post (the high-E post sits on the treble side of the centre line);
    //   S-curved treble edge with a belly near the nut, a hook and a round bulb at the tip.
    //   Proportions from a 1:1 luthier template.
    inline constexpr HeadPt strat_inline6_outline[] = {
        { 0, 21.5f, true }, { 12.84f, 23.31f }, { 22, 26.5f }, { 29.59f, 30.73f }, { 40, 38.6f }, { 47.78f, 44.39f },
        { 51.36f, 45.85f }, { 55, 46.3f }, { 64.55f, 45.69f }, { 74.68f, 43.69f }, { 90, 39.6f }, { 105.1f, 35.32f },
        { 118, 32 }, { 127.5f, 30.4f }, { 128.75f, 30.61f }, { 129.98f, 31.3f }, { 131.53f, 32.96f }, { 135.6f, 40.7f },
        { 137.77f, 43.86f }, { 140.53f, 46.31f }, { 147, 49.8f }, { 152.79f, 51.79f }, { 160, 52.4f }, { 168.36f, 51.81f },
        { 172.44f, 50.43f }, { 176, 48.1f }, { 179.53f, 44.38f }, { 181.78f, 40.33f }, { 183.5f, 34 }, { 183.92f, 27.71f },
        { 182.5f, 20 }, { 180.44f, 15.09f }, { 177.11f, 10.95f }, { 171, 6.5f, true }, { 40, -32.5f }, { 31.44f, -35.14f },
        { 27, -35.6f }, { 22.77f, -35 }, { 19.5f, -33.43f }, { 16, -30.2f }, { 14, -28.51f }, { 8.84f, -26.12f },
        { 7.02f, -24.73f }, { 6, -23.2f }, { 5.31f, -22.51f }, { 1.54f, -22.3f }, { 0.53f, -22.19f }, { 0, -21.5f, true } };
    inline constexpr HeadPt strat_inline6_posts[] = {
        { 42, -18 }, { 64.6f, -11.4f }, { 87.2f, -4.8f }, { 109.8f, 1.8f }, { 132.4f, 8.4f }, { 155, 15 } };
    inline constexpr HeadPt strat_inline6_buttons[] = {
        { 49.7f, -43.88f }, { 72.3f, -37.28f }, { 94.9f, -30.68f }, { 117.5f, -24.08f }, { 140.1f, -17.48f }, { 162.7f, -10.88f } };

    // tele_inline6
    //   Smaller slanted paddle: the same straight-pull post line, a straight treble edge and a
    //   blunt end cut back toward the bass side with a rounded treble corner.
    inline constexpr HeadPt tele_inline6_outline[] = {
        { 0, 21.5f, true }, { 11.62f, 23.04f }, { 18, 25.5f }, { 23.63f, 27.92f }, { 29.75f, 29.36f }, { 42, 30.5f },
        { 63.16f, 31.64f }, { 85.53f, 31.54f }, { 110, 31.2f }, { 129.31f, 31.53f }, { 150, 32.5f }, { 158.86f, 32.45f },
        { 161.92f, 31.48f }, { 164.17f, 29.88f }, { 166, 27.5f }, { 168.64f, 21.96f }, { 169.25f, 18.71f }, { 169, 15 },
        { 168.34f, 12.92f }, { 166.99f, 10.76f }, { 163, 7 }, { 161.28f, 5.88f }, { 158.14f, 4.68f }, { 150, 3 },
        { 36, -31.5f }, { 28.59f, -33.44f }, { 24, -33.8f }, { 19.72f, -33.33f }, { 16.67f, -32.2f }, { 14.19f, -30.49f },
        { 12, -28 }, { 10.79f, -26.78f }, { 8.68f, -25.7f }, { 2.42f, -24.05f }, { 0.91f, -23.3f }, { 0, -21.5f, true } };
    inline constexpr HeadPt tele_inline6_posts[] = {
        { 40, -18.5f }, { 62.2f, -12.2f }, { 84.4f, -5.9f }, { 106.6f, 0.4f }, { 128.8f, 6.7f }, { 151, 13 } };
    inline constexpr HeadPt tele_inline6_buttons[] = {
        { 47.53f, -43.39f }, { 69.73f, -37.09f }, { 91.93f, -30.79f }, { 114.13f, -24.49f }, { 136.33f, -18.19f }, { 158.53f, -11.89f } };

    // offset_inline6
    //   The larger Fender offset headstock: the Strat's geometry with a fuller treble belly
    //   and a bigger bulb.
    inline constexpr HeadPt offset_inline6_outline[] = {
        { 0, 21.5f, true }, { 11.19f, 23.4f }, { 22, 27.5f }, { 30.13f, 32.36f }, { 42, 41.5f }, { 51.29f, 48.17f },
        { 55.66f, 49.96f }, { 60, 50.5f }, { 69.34f, 49.87f }, { 79.48f, 47.76f }, { 95, 43.5f }, { 110.64f, 38.72f },
        { 124, 35 }, { 130.6f, 33.59f }, { 133, 33.4f }, { 134.37f, 33.63f }, { 135.73f, 34.36f }, { 137.56f, 36.29f },
        { 142, 44.5f }, { 144.33f, 47.86f }, { 147.32f, 50.46f }, { 155, 54.5f }, { 161.68f, 56.8f }, { 170, 57.5f },
        { 177.13f, 56.78f }, { 181.65f, 55.09f }, { 186, 52 }, { 189.17f, 48.37f }, { 191.26f, 44.1f }, { 193, 36 },
        { 193.17f, 29.04f }, { 191, 20 }, { 188.97f, 15.81f }, { 185.78f, 12.21f }, { 178, 7, true }, { 40, -33.5f },
        { 31.51f, -35.97f }, { 27, -36.4f }, { 22.98f, -35.82f }, { 19.7f, -34.24f }, { 16, -30.8f }, { 13.92f, -29.01f },
        { 8.85f, -26.44f }, { 7.03f, -24.98f }, { 6, -23.4f }, { 5.31f, -22.69f }, { 4.54f, -22.44f }, { 1.49f, -22.36f },
        { 0.53f, -22.21f }, { 0, -21.5f, true } };
    inline constexpr HeadPt offset_inline6_posts[] = {
        { 42, -18.5f }, { 65.2f, -11.7f }, { 88.4f, -4.9f }, { 111.6f, 1.9f }, { 134.8f, 8.7f }, { 158, 15.5f } };
    inline constexpr HeadPt offset_inline6_buttons[] = {
        { 49.6f, -44.41f }, { 72.8f, -37.61f }, { 96, -30.81f }, { 119.2f, -24.01f }, { 142.4f, -17.21f }, { 165.6f, -10.41f } };

    // superstrat_inline6
    //   Pointed, drooping in-line headstock: long treble sweep curving up to a point at the
    //   end of a straight bass edge; posts on a line slanting 6 deg toward the treble side.
    inline constexpr HeadPt superstrat_inline6_outline[] = {
        { 0, 21.5f, true }, { 12.74f, 22.61f }, { 20, 24.5f }, { 27.26f, 26.45f }, { 35.82f, 27.2f }, { 50, 27.5f },
        { 70.12f, 28.58f }, { 90.19f, 28.97f }, { 112.2f, 29 }, { 134.75f, 28.92f }, { 149.54f, 27.43f }, { 163.2f, 24 },
        { 176.54f, 19.15f }, { 183.55f, 15.2f }, { 189.72f, 10 }, { 196.07f, 2.07f }, { 204, -12.83f, true }, { 34, -30.69f },
        { 23.29f, -31.91f }, { 18, -31.19f }, { 11.24f, -28.8f }, { 8.74f, -26.91f }, { 7, -24.5f }, { 5.85f, -23.47f },
        { 4.25f, -23.04f }, { 0.94f, -22.59f }, { 0, -21.5f, true } };
    inline constexpr HeadPt superstrat_inline6_posts[] = {
        { 40, -18.5f }, { 62.4f, -16.15f }, { 84.8f, -13.79f }, { 107.2f, -11.44f }, { 129.6f, -9.08f }, { 152, -6.73f } };
    inline constexpr HeadPt superstrat_inline6_buttons[] = {
        { 42.61f, -43.36f }, { 65.01f, -41.01f }, { 87.41f, -38.65f }, { 109.81f, -36.3f }, { 132.21f, -33.95f }, { 154.61f, -31.59f } };

    // reverse_inline6
    //   guitar-illustration.md 6's reverse 6-in-line: the pointed in-line head mirrored across
    //   the strings, so its tuners run along the treble edge and the low E post is the far one.
    inline constexpr HeadPt reverse_inline6_outline[] = {
        { 0, 21.5f, true }, { 0.47f, 22.37f }, { 4.37f, 23.06f }, { 5.95f, 23.52f }, { 7, 24.5f }, { 8.85f, 27.02f },
        { 11.38f, 28.88f }, { 18, 31.19f }, { 23.38f, 31.91f }, { 34, 30.69f }, { 204, 12.83f, true }, { 195.99f, -2.21f },
        { 189.72f, -10 }, { 183.4f, -15.3f }, { 176.21f, -19.3f }, { 163.2f, -24 }, { 148.92f, -27.54f }, { 134.14f, -28.94f },
        { 112.2f, -29 }, { 89.82f, -28.97f }, { 69.74f, -28.57f }, { 50, -27.5f }, { 35.64f, -27.2f }, { 26.89f, -26.38f },
        { 20, -24.5f }, { 12.48f, -22.57f }, { 0, -21.5f, true } };
    inline constexpr HeadPt reverse_inline6_posts[] = {
        { 152, 6.73f }, { 129.6f, 9.08f }, { 107.2f, 11.44f }, { 84.8f, 13.79f }, { 62.4f, 16.15f }, { 40, 18.5f } };
    inline constexpr HeadPt reverse_inline6_buttons[] = {
        { 154.61f, 31.59f }, { 132.21f, 33.95f }, { 109.81f, 36.3f }, { 87.41f, 38.65f }, { 65.01f, 41.01f }, { 42.61f, 43.36f } };

    // inline7
    //   Seven-string pointed in-line headstock.
    inline constexpr HeadPt inline7_outline[] = {
        { 0, 21.5f, true }, { 12.74f, 22.61f }, { 20, 24.5f }, { 27.26f, 26.45f }, { 35.82f, 27.2f }, { 50, 27.5f },
        { 74.03f, 28.72f }, { 98.01f, 29.05f }, { 124.3f, 29 }, { 148.94f, 29.13f }, { 165.67f, 27.71f }, { 180.8f, 24 },
        { 196.62f, 18.85f }, { 204.06f, 15.01f }, { 210.18f, 10 }, { 220.5f, -1.2f }, { 226, -9.65f, true }, { 34, -31.53f },
        { 23.29f, -32.75f }, { 18, -32.03f }, { 12.05f, -29.75f }, { 9.15f, -27.5f }, { 7, -24.5f }, { 5.85f, -23.47f },
        { 4.25f, -23.04f }, { 0.94f, -22.59f }, { 0, -21.5f, true } };
    inline constexpr HeadPt inline7_posts[] = {
        { 38, -19.5f }, { 59, -17.11f }, { 80, -14.71f }, { 101, -12.32f }, { 122, -9.93f }, { 143, -7.54f },
        { 164, -5.14f } };
    inline constexpr HeadPt inline7_buttons[] = {
        { 40.83f, -44.34f }, { 61.83f, -41.95f }, { 82.83f, -39.55f }, { 103.83f, -37.16f }, { 124.83f, -34.77f }, { 145.83f, -32.38f },
        { 166.83f, -29.98f } };

    // inline8
    //   Eight-string pointed in-line headstock.
    inline constexpr HeadPt inline8_outline[] = {
        { 0, 21.5f, true }, { 12.74f, 22.61f }, { 20, 24.5f }, { 27.26f, 26.45f }, { 35.82f, 27.2f }, { 50, 27.5f },
        { 71.1f, 28.64f }, { 91.66f, 29.1f }, { 113.65f, 29.09f }, { 136.4f, 29 }, { 157.48f, 29.32f }, { 173.31f, 28.94f },
        { 185.97f, 27.25f }, { 198.4f, 24 }, { 215.94f, 18.93f }, { 224.33f, 15.04f }, { 230.64f, 10 }, { 239.3f, 3.23f },
        { 245.33f, -1.77f }, { 248, -5.56f, true }, { 34, -31.83f }, { 23.29f, -33.07f }, { 18, -32.33f }, { 12.39f, -30.14f },
        { 9.33f, -27.76f }, { 7, -24.5f }, { 5.85f, -23.47f }, { 4.25f, -23.04f }, { 0.94f, -22.59f }, { 0, -21.5f, true } };
    inline constexpr HeadPt inline8_posts[] = {
        { 36, -20 }, { 56.5f, -17.48f }, { 77, -14.97f }, { 97.5f, -12.45f }, { 118, -9.93f }, { 138.5f, -7.41f },
        { 159, -4.9f }, { 179.5f, -2.38f } };
    inline constexpr HeadPt inline8_buttons[] = {
        { 39.05f, -44.81f }, { 59.55f, -42.3f }, { 80.05f, -39.78f }, { 100.55f, -37.26f }, { 121.05f, -34.75f }, { 141.55f, -32.23f },
        { 162.05f, -29.71f }, { 182.55f, -27.19f } };

    // explorer_hockey
    //   "Hockey stick": long and narrow, tuners along a straight bass edge that slants toward
    //   the treble side, the end hooked toward the treble side like a stick's blade.
    inline constexpr HeadPt explorer_hockey_outline[] = {
        { 0, 21.5f, true }, { 9.43f, 22.8f }, { 16, 24.5f }, { 24.88f, 26.47f }, { 40, 27.5f }, { 61.36f, 29.01f },
        { 83.43f, 29.92f }, { 107.22f, 30.6f }, { 129.33f, 31.53f }, { 150, 33 }, { 173.12f, 35.7f }, { 196, 40 },
        { 212.41f, 43.21f }, { 222, 44, true }, { 220.79f, 36.37f }, { 219.59f, 32.5f }, { 218, 30 }, { 214.4f, 26.52f },
        { 210.2f, 23.92f }, { 200, 20 }, { 187.17f, 14 }, { 178, 10 }, { 30, -30 }, { 23.87f, -31.16f },
        { 20, -31.03f }, { 16, -30 }, { 9.34f, -27.44f }, { 7.39f, -25.93f }, { 6, -24 }, { 5.02f, -23.13f },
        { 3.69f, -22.78f }, { 0.77f, -22.41f }, { 0, -21.5f, true } };
    inline constexpr HeadPt explorer_hockey_posts[] = {
        { 40, -17.5f }, { 64, -11 }, { 88, -4.5f }, { 112, 2 }, { 136, 8.5f }, { 160, 15 } };
    inline constexpr HeadPt explorer_hockey_buttons[] = {
        { 46.52f, -41.63f }, { 70.52f, -35.13f }, { 94.52f, -28.63f }, { 118.52f, -22.13f }, { 142.52f, -15.63f }, { 166.52f, -9.13f } };
    inline constexpr HeadPt explorer_hockey_truss[] = {
        { 8, -4.5f }, { 8, 4.5f }, { 9.69f, 4.99f }, { 11.74f, 5.34f }, { 15.23f, 5.66f }, { 18.83f, 6.01f },
        { 21.3f, 6.43f }, { 23.4f, 7 }, { 25.63f, 7.86f }, { 28.09f, 8.88f }, { 29.51f, 9.28f }, { 31, 9.5f },
        { 31.97f, 9.5f }, { 33.27f, 9.12f }, { 34.27f, 8.32f }, { 35.16f, 6.77f }, { 35.56f, 5.39f }, { 35.87f, 3.27f },
        { 36, 0 }, { 35.88f, -3.1f }, { 35.6f, -5.04f }, { 35.23f, -6.3f }, { 34.81f, -7.21f }, { 33.88f, -8.38f },
        { 32.69f, -9.11f }, { 31, -9.5f }, { 29.77f, -9.5f }, { 28.73f, -9.32f }, { 27.56f, -8.92f }, { 25.09f, -7.69f },
        { 23.4f, -7 }, { 21.2f, -6.41f }, { 18.62f, -5.98f }, { 15.14f, -5.66f }, { 11.65f, -5.33f }, { 9.52f, -4.95f } };

    // firebird_inline6
    //   Firebird-style in-line headstock: banjo tuners along the bass edge (keys seen edge-on),
    //   a long straight treble edge and a round crown on the bass side.
    inline constexpr HeadPt firebird_inline6_outline[] = {
        { 0, 21.5f, true }, { 10.6f, 23.04f }, { 20, 26 }, { 29.76f, 29.01f }, { 45, 31 }, { 70.6f, 33.15f },
        { 96.2f, 34.07f }, { 122.35f, 33.86f }, { 150, 33 }, { 168.56f, 33.16f }, { 180.2f, 32.49f }, { 188.42f, 30.49f },
        { 196, 27 }, { 204.52f, 21.33f }, { 208.68f, 17.12f }, { 211.69f, 12.32f }, { 214, 6 }, { 214.95f, -0.1f },
        { 214.51f, -5.01f }, { 212.79f, -10.08f }, { 208, -18 }, { 206.78f, -19.26f }, { 205.54f, -19.89f }, { 203.85f, -20.17f },
        { 200.79f, -19.77f }, { 192.5f, -17.2f }, { 190, -17 }, { 34, -29 }, { 24.11f, -30.41f }, { 19.69f, -30.4f },
        { 16, -29.5f }, { 9.29f, -27.19f }, { 7.33f, -25.8f }, { 6, -24 }, { 5.02f, -23.13f }, { 3.69f, -22.78f },
        { 0.77f, -22.41f }, { 0, -21.5f, true } };
    inline constexpr HeadPt firebird_inline6_posts[] = {
        { 44, -18 }, { 70.4f, -15.8f }, { 96.8f, -13.6f }, { 123.2f, -11.4f }, { 149.6f, -9.2f }, { 176, -7 } };
    inline constexpr HeadPt firebird_inline6_buttons[] = {
        { 42.6f, -37.95f }, { 69, -35.75f }, { 95.4f, -33.55f }, { 121.8f, -31.35f }, { 148.2f, -29.15f }, { 174.6f, -26.95f } };

    // lp_33
    //   Open-book 3+3: flares from the nut to ~68 mm, near-parallel sides widening slightly to
    //   ~78 mm, square-ish top corners and a top edge rising to two peaks either side of a
    //   small central notch; ~170 mm long. From a 1:1 luthier template.
    inline constexpr HeadPt lp_33_outline[] = {
        { 0, 21.5f, true }, { 7.88f, 22.71f }, { 12, 24 }, { 20.38f, 27.21f }, { 24, 29.6f }, { 28.62f, 32.74f },
        { 33, 34.2f }, { 39.68f, 35 }, { 48.48f, 34.48f }, { 60, 33.6f }, { 79.77f, 33.8f }, { 100, 34.4f },
        { 118.28f, 35.57f }, { 138.87f, 37.67f }, { 157, 39.2f, true }, { 158.19f, 37.13f }, { 162.3f, 32.25f }, { 163.87f, 29.59f },
        { 164.5f, 27.5f }, { 166.37f, 21.11f }, { 169.07f, 13.32f }, { 169.5f, 9.5f }, { 169, 4.49f }, { 168.04f, 1.63f },
        { 167, 0, true }, { 168.09f, -1.74f }, { 169.03f, -4.62f }, { 169.5f, -9.5f }, { 169.03f, -13.54f }, { 166.29f, -21.32f },
        { 164.5f, -27.5f }, { 163.8f, -29.76f }, { 162.19f, -32.4f }, { 158.1f, -37.26f }, { 157, -39.2f, true }, { 138.53f, -37.63f },
        { 117.91f, -35.54f }, { 100, -34.4f }, { 79.54f, -33.79f }, { 60, -33.6f }, { 48.32f, -34.5f }, { 39.35f, -34.99f },
        { 33, -34.2f }, { 28.51f, -32.69f }, { 24, -29.6f }, { 20.24f, -27.14f }, { 12, -24 }, { 9.48f, -23.45f },
        { 2.74f, -23.45f }, { 1.15f, -23.15f }, { 0.28f, -22.51f }, { 0, -21.5f, true } };
    inline constexpr HeadPt lp_33_posts[] = {
        { 52, -25 }, { 89, -26 }, { 126, -27 }, { 126, 27 }, { 89, 26 }, { 52, 25 } };
    inline constexpr HeadPt lp_33_buttons[] = {
        { 52, -53 }, { 89, -54 }, { 126, -55 }, { 126, 55 }, { 89, 54 }, { 52, 53 } };
    inline constexpr HeadPt lp_33_truss[] = {
        { 6, -5 }, { 6, 5 }, { 8.17f, 5.65f }, { 10.83f, 6.16f }, { 14.27f, 6.57f }, { 18.87f, 6.99f },
        { 22.34f, 7.43f }, { 25.44f, 8.03f }, { 28, 8.75f }, { 32.1f, 10.23f }, { 35.65f, 11.48f }, { 38.3f, 12.13f },
        { 41, 12.5f }, { 42.11f, 12.5f }, { 43.39f, 12.13f }, { 44.3f, 11.44f }, { 45.08f, 10.24f }, { 45.47f, 9.12f },
        { 45.79f, 7.44f }, { 45.98f, 4.63f }, { 46, 0 }, { 45.97f, -4.73f }, { 45.76f, -7.36f }, { 45.42f, -8.93f },
        { 45.01f, -9.98f }, { 44.58f, -10.69f }, { 43.52f, -11.71f }, { 42.03f, -12.34f }, { 41, -12.5f }, { 39.18f, -12.54f },
        { 37.55f, -12.37f }, { 35.88f, -11.96f }, { 33.87f, -11.21f }, { 30.47f, -9.69f }, { 28, -8.75f }, { 25.15f, -7.96f },
        { 22.19f, -7.4f }, { 18.58f, -6.96f }, { 14.14f, -6.55f }, { 10.57f, -6.12f }, { 8.05f, -5.62f } };

    // sg_33
    //   The same open book, a touch narrower and shorter.
    inline constexpr HeadPt sg_33_outline[] = {
        { 0, 21.5f, true }, { 7.96f, 22.58f }, { 12, 23.8f }, { 20.46f, 26.61f }, { 24, 28.8f }, { 28.58f, 32.03f },
        { 32, 33.2f }, { 38.93f, 34.06f }, { 48.05f, 33.63f }, { 60, 32.8f }, { 79.77f, 33 }, { 100, 33.6f },
        { 116.68f, 34.63f }, { 135.46f, 36.45f }, { 152, 37.8f, true }, { 153.95f, 34.73f }, { 158.04f, 29.31f }, { 159, 26.5f },
        { 160.82f, 20.39f }, { 163.57f, 12.72f }, { 164, 9 }, { 163.53f, 4.5f }, { 162.55f, 1.65f }, { 161.5f, 0, true },
        { 162.6f, -1.75f }, { 163.55f, -4.61f }, { 164, -9 }, { 163.52f, -12.93f }, { 160.77f, -20.49f }, { 159, -26.5f },
        { 157.96f, -29.46f }, { 153.85f, -34.86f }, { 152, -37.8f, true }, { 135.15f, -36.42f }, { 116.34f, -34.6f }, { 100, -33.6f },
        { 79.54f, -32.99f }, { 60, -32.8f }, { 47.72f, -33.66f }, { 38.58f, -34.05f }, { 32, -33.2f }, { 28.48f, -31.98f },
        { 24, -28.8f }, { 20.32f, -26.54f }, { 12, -23.8f }, { 9.58f, -23.28f }, { 2.74f, -23.38f }, { 1.15f, -23.12f },
        { 0.28f, -22.5f }, { 0, -21.5f, true } };
    inline constexpr HeadPt sg_33_posts[] = {
        { 51, -24.5f }, { 87, -25.5f }, { 123, -26.5f }, { 123, 26.5f }, { 87, 25.5f }, { 51, 24.5f } };
    inline constexpr HeadPt sg_33_buttons[] = {
        { 51, -52.5f }, { 87, -53.5f }, { 123, -54.5f }, { 123, 54.5f }, { 87, 53.5f }, { 51, 52.5f } };
    inline constexpr HeadPt sg_33_truss[] = {
        { 6, -5 }, { 6, 5 }, { 8.42f, 5.7f }, { 11.45f, 6.21f }, { 16.08f, 6.65f }, { 20.55f, 7.11f },
        { 24.05f, 7.72f }, { 26.9f, 8.5f }, { 30.78f, 9.91f }, { 34.02f, 11.05f }, { 36.49f, 11.66f }, { 39, 12 },
        { 40.08f, 12 }, { 41.32f, 11.65f }, { 42.22f, 10.99f }, { 43.03f, 9.77f }, { 43.42f, 8.69f }, { 43.75f, 7.07f },
        { 43.96f, 4.46f }, { 44, 0 }, { 43.95f, -4.55f }, { 43.72f, -6.99f }, { 43.37f, -8.5f }, { 42.96f, -9.52f },
        { 42.5f, -10.27f }, { 41.51f, -11.2f }, { 39.99f, -11.84f }, { 39, -12 }, { 37.31f, -12.04f }, { 35.78f, -11.87f },
        { 34.31f, -11.52f }, { 32.43f, -10.83f }, { 29.2f, -9.38f }, { 26.9f, -8.5f }, { 23.77f, -7.66f }, { 20.41f, -7.09f },
        { 15.95f, -6.64f }, { 11.33f, -6.2f }, { 8.3f, -5.67f } };

    // v_33
    //   Flying-V "arrowhead": narrow 3+3 whose sides run out to a point on the centre line.
    inline constexpr HeadPt v_33_outline[] = {
        { 0, 21.5f, true }, { 9.33f, 22.88f }, { 14, 24.5f }, { 23.66f, 29.08f }, { 30, 31.5f }, { 46.52f, 35.53f },
        { 63.79f, 37.08f }, { 87.24f, 36.64f }, { 110, 36.5f }, { 125.21f, 37.09f }, { 133.95f, 36.6f }, { 142, 35 },
        { 154.56f, 30.31f }, { 167.42f, 22.89f }, { 183.69f, 10.69f }, { 198, 0, true }, { 183.38f, -10.94f }, { 167.05f, -23.13f },
        { 153.73f, -30.7f }, { 142, -35 }, { 133.75f, -36.62f }, { 124.84f, -37.09f }, { 110, -36.5f }, { 86.74f, -36.66f },
        { 62.85f, -37.05f }, { 45.53f, -35.37f }, { 30, -31.5f }, { 23.56f, -29.04f }, { 14, -24.5f }, { 11.44f, -23.8f },
        { 3.7f, -23.76f }, { 1.43f, -23.43f }, { 0.71f, -23.07f }, { 0, -21.5f, true } };
    inline constexpr HeadPt v_33_posts[] = {
        { 48, -24 }, { 84, -24.5f }, { 120, -25 }, { 120, 25 }, { 84, 24.5f }, { 48, 24 } };
    inline constexpr HeadPt v_33_buttons[] = {
        { 48, -52 }, { 84, -52.5f }, { 120, -53 }, { 120, 53 }, { 84, 52.5f }, { 48, 52 } };
    inline constexpr HeadPt v_33_truss[] = {
        { 6, -4.5f }, { 6, 4.5f }, { 8.29f, 5.16f }, { 11.05f, 5.62f }, { 15.43f, 6.02f }, { 19.79f, 6.45f },
        { 23.1f, 7.02f }, { 25.8f, 7.75f }, { 29.39f, 9.05f }, { 32.46f, 10.13f }, { 34.68f, 10.68f }, { 37, 11 },
        { 38.01f, 11 }, { 39.25f, 10.66f }, { 40.16f, 10 }, { 40.94f, 8.85f }, { 41.33f, 7.85f }, { 41.67f, 6.34f },
        { 41.93f, 3.82f }, { 42, 0 }, { 41.92f, -3.92f }, { 41.66f, -6.19f }, { 41.28f, -7.68f }, { 40.87f, -8.62f },
        { 40.42f, -9.32f }, { 39.43f, -10.24f }, { 38.01f, -10.84f }, { 37, -11 }, { 35.13f, -11.02f }, { 33.53f, -10.78f },
        { 31.75f, -10.24f }, { 28.47f, -8.8f }, { 25.8f, -7.75f }, { 22.83f, -6.96f }, { 19.66f, -6.43f }, { 15.3f, -6.01f },
        { 10.93f, -5.61f }, { 8.07f, -5.11f } };

    // acoustic_33
    //   Square flat-top headstock: quick shoulders at the nut, straight sides flaring slightly
    //   toward the tip, small-radius corners and a straight top edge.
    inline constexpr HeadPt acoustic_33_outline[] = {
        { 0, 21.5f, true }, { 4.08f, 22.65f }, { 7.33f, 24.33f }, { 10, 26.5f }, { 15.6f, 31.33f }, { 20, 33.5f },
        { 26.87f, 35.06f }, { 40, 35.2f }, { 64.1f, 35.99f }, { 88.1f, 36.68f }, { 112.6f, 37.34f }, { 136.66f, 38.04f },
        { 160, 38.8f }, { 166.97f, 39.19f }, { 168.97f, 38.78f }, { 170.23f, 38.08f }, { 171.18f, 37.09f }, { 172, 35.5f },
        { 174.04f, 28.28f }, { 174.5f, 20 }, { 174.5f, -20 }, { 174.02f, -28.37f }, { 172, -35.5f }, { 171.08f, -37.23f },
        { 170.11f, -38.17f }, { 168.83f, -38.83f }, { 166.81f, -39.2f }, { 160, -38.8f }, { 135.9f, -38.01f }, { 111.9f, -37.32f },
        { 87.4f, -36.66f }, { 63.34f, -35.96f }, { 40, -35.2f }, { 26.76f, -35.05f }, { 20, -33.5f }, { 15.48f, -31.26f },
        { 10, -26.5f }, { 8.42f, -25.41f }, { 3.02f, -23.94f }, { 0.94f, -23.15f }, { 0, -21.5f, true } };
    inline constexpr HeadPt acoustic_33_posts[] = {
        { 50, -26 }, { 85, -26.8f }, { 120, -27.6f }, { 120, 27.6f }, { 85, 26.8f }, { 50, 26 } };
    inline constexpr HeadPt acoustic_33_buttons[] = {
        { 50, -54 }, { 85, -54.8f }, { 120, -55.6f }, { 120, 55.6f }, { 85, 54.8f }, { 50, 54 } };
    inline constexpr HeadPt acoustic_33_truss[] = {
        { 4, -7 }, { 3.86f, -5.39f }, { 3.18f, -2.01f }, { 2.37f, 1.91f }, { 2.14f, 3.97f }, { 2.18f, 5.1f },
        { 2.47f, 6.13f }, { 3.08f, 6.79f }, { 4, 7 }, { 6.07f, 7.18f }, { 9.68f, 7.89f }, { 14.45f, 8.92f },
        { 17.48f, 9.36f }, { 19.13f, 9.38f }, { 20.13f, 9.24f }, { 21.22f, 8.76f }, { 21.86f, 7.89f }, { 22, 7 },
        { 22.14f, 5.39f }, { 22.82f, 2.01f }, { 23.63f, -1.91f }, { 23.86f, -3.97f }, { 23.82f, -5.1f }, { 23.53f, -6.13f },
        { 22.92f, -6.79f }, { 22, -7 }, { 19.93f, -7.18f }, { 16.32f, -7.89f }, { 11.55f, -8.92f }, { 8.52f, -9.36f },
        { 6.87f, -9.38f }, { 5.87f, -9.24f }, { 4.78f, -8.76f }, { 4.14f, -7.89f } };

    // archtop_33
    //   Larger, ornate flared headstock: concave sides widening to ~94 mm, rounded top corners
    //   and a top edge with a raised centre between two shallow scallops.
    inline constexpr HeadPt archtop_33_outline[] = {
        { 0, 21.5f, true }, { 8.87f, 23.13f }, { 14, 25 }, { 25.2f, 29.37f }, { 40, 33 }, { 57.84f, 35.83f },
        { 79.82f, 37.49f }, { 100, 39.5f }, { 120.16f, 41.8f }, { 141.73f, 43.87f }, { 160, 46.5f }, { 171.24f, 48.65f },
        { 175.94f, 48.72f }, { 179.92f, 47.86f }, { 184, 46 }, { 188.83f, 42.45f }, { 190.9f, 39.71f }, { 191.86f, 37.05f },
        { 192, 34 }, { 191.24f, 30.77f }, { 188.52f, 24.88f }, { 187.9f, 22.31f }, { 188, 20 }, { 188.66f, 17.86f },
        { 189.88f, 15.9f }, { 193.97f, 11.7f }, { 196, 9 }, { 199.03f, 4.15f }, { 199.76f, 2.14f }, { 200, 0 },
        { 199.73f, -2.26f }, { 198.98f, -4.25f }, { 196, -9 }, { 193.85f, -11.83f }, { 189.78f, -16.03f }, { 188.6f, -18.01f },
        { 188, -20 }, { 187.92f, -22.49f }, { 188.59f, -25.05f }, { 191.31f, -30.95f }, { 192, -34 }, { 191.82f, -37.23f },
        { 190.82f, -39.86f }, { 188.7f, -42.58f }, { 184, -46 }, { 179.61f, -47.96f }, { 175.65f, -48.74f }, { 170.96f, -48.62f },
        { 160, -46.5f }, { 141.37f, -43.83f }, { 119.8f, -41.77f }, { 100, -39.5f }, { 79.46f, -37.46f }, { 57.47f, -35.79f },
        { 40, -33 }, { 25.05f, -29.33f }, { 14, -25 }, { 11.31f, -24.25f }, { 3.59f, -23.94f }, { 1.42f, -23.52f },
        { 0.71f, -23.12f }, { 0, -21.5f, true } };
    inline constexpr HeadPt archtop_33_posts[] = {
        { 56, -27 }, { 94, -29.5f }, { 132, -32 }, { 132, 32 }, { 94, 29.5f }, { 56, 27 } };
    inline constexpr HeadPt archtop_33_buttons[] = {
        { 56, -55 }, { 94, -57.5f }, { 132, -60 }, { 132, 60 }, { 94, 57.5f }, { 56, 55 } };
    inline constexpr HeadPt archtop_33_truss[] = {
        { 6, -5 }, { 6, 5 }, { 8.17f, 5.65f }, { 10.83f, 6.16f }, { 14.27f, 6.57f }, { 18.87f, 6.99f },
        { 22.34f, 7.43f }, { 25.44f, 8.03f }, { 28, 8.75f }, { 32.1f, 10.23f }, { 35.65f, 11.48f }, { 38.3f, 12.13f },
        { 41, 12.5f }, { 42.11f, 12.5f }, { 43.39f, 12.13f }, { 44.3f, 11.44f }, { 45.08f, 10.24f }, { 45.47f, 9.12f },
        { 45.79f, 7.44f }, { 45.98f, 4.63f }, { 46, 0 }, { 45.97f, -4.73f }, { 45.76f, -7.36f }, { 45.42f, -8.93f },
        { 45.01f, -9.98f }, { 44.58f, -10.69f }, { 43.52f, -11.71f }, { 42.03f, -12.34f }, { 41, -12.5f }, { 39.18f, -12.54f },
        { 37.55f, -12.37f }, { 35.88f, -11.96f }, { 33.87f, -11.21f }, { 30.47f, -9.69f }, { 28, -8.75f }, { 25.15f, -7.96f },
        { 22.19f, -7.4f }, { 18.58f, -6.96f }, { 14.14f, -6.55f }, { 10.57f, -6.12f }, { 8.05f, -5.62f } };

    // twelve_66
    //   Twelve-string 6+6: the square acoustic headstock stretched to take six tuners a side;
    //   posts in course pairs, lowest course nearest the nut.
    inline constexpr HeadPt twelve_66_outline[] = {
        { 0, 21.5f, true }, { 3.32f, 22.47f }, { 6.69f, 24.27f }, { 10, 27 }, { 17.06f, 33.19f }, { 22, 35.5f },
        { 30.36f, 37.22f }, { 45, 37.5f }, { 73.54f, 38.41f }, { 101.73f, 39.12f }, { 129.49f, 39.67f }, { 157.25f, 40.11f },
        { 186.54f, 40.55f }, { 214, 41 }, { 220.9f, 41.28f }, { 222.97f, 40.82f }, { 224.23f, 40.1f }, { 225.18f, 39.1f },
        { 226, 37.5f }, { 228.44f, 28.95f }, { 229, 20 }, { 229, -20 }, { 228.43f, -29.05f }, { 226, -37.5f },
        { 225.08f, -39.24f }, { 224.11f, -40.2f }, { 222.83f, -40.88f }, { 220.73f, -41.29f }, { 214, -41 }, { 185.45f, -40.53f },
        { 156.24f, -40.1f }, { 128.51f, -39.65f }, { 100.72f, -39.1f }, { 72.45f, -38.38f }, { 45, -37.5f }, { 30.09f, -37.19f },
        { 22, -35.5f }, { 16.91f, -33.09f }, { 10, -27 }, { 8.32f, -25.83f }, { 2.85f, -24.1f }, { 0.98f, -23.27f },
        { 0.37f, -22.68f }, { 0, -21.5f, true } };
    inline constexpr HeadPt twelve_66_posts[] = {
        { 40, -27 }, { 62.5f, -27.3f }, { 85, -27.6f }, { 107.5f, -27.9f }, { 130, -28.2f }, { 152.5f, -28.5f },
        { 152.5f, 28.5f }, { 130, 28.2f }, { 107.5f, 27.9f }, { 85, 27.6f }, { 62.5f, 27.3f }, { 40, 27 } };
    inline constexpr HeadPt twelve_66_buttons[] = {
        { 40, -52 }, { 62.5f, -52.3f }, { 85, -52.6f }, { 107.5f, -52.9f }, { 130, -53.2f }, { 152.5f, -53.5f },
        { 152.5f, 53.5f }, { 130, 53.2f }, { 107.5f, 52.9f }, { 85, 52.6f }, { 62.5f, 52.3f }, { 40, 52 } };
    inline constexpr HeadPt twelve_66_truss[] = {
        { 4, -7 }, { 3.86f, -5.39f }, { 3.18f, -2.01f }, { 2.37f, 1.91f }, { 2.14f, 3.97f }, { 2.18f, 5.1f },
        { 2.47f, 6.13f }, { 3.08f, 6.79f }, { 4, 7 }, { 6.07f, 7.18f }, { 9.68f, 7.89f }, { 14.45f, 8.92f },
        { 17.48f, 9.36f }, { 19.13f, 9.38f }, { 20.13f, 9.24f }, { 21.22f, 8.76f }, { 21.86f, 7.89f }, { 22, 7 },
        { 22.14f, 5.39f }, { 22.82f, 2.01f }, { 23.63f, -1.91f }, { 23.86f, -3.97f }, { 23.82f, -5.1f }, { 23.53f, -6.13f },
        { 22.92f, -6.79f }, { 22, -7 }, { 19.93f, -7.18f }, { 16.32f, -7.89f }, { 11.55f, -8.92f }, { 8.52f, -9.36f },
        { 6.87f, -9.38f }, { 5.87f, -9.24f }, { 4.78f, -8.76f }, { 4.14f, -7.89f } };

    // classical_slotted
    //   Spanish slotted headstock: parallel sides ~58 mm apart, two slots with three rollers
    //   each (35 mm spacing), keys out the sides, and a scalloped crown at the top.
    inline constexpr HeadPt classical_slotted_outline[] = {
        { 0, 21.5f, true }, { 4.62f, 23.12f }, { 9, 26 }, { 11.43f, 27.56f }, { 14.27f, 28.43f }, { 22, 29 },
        { 45.98f, 30.62f }, { 69.82f, 31.29f }, { 93.34f, 31.14f }, { 119.38f, 30.45f }, { 144.98f, 29.77f }, { 170, 29.5f },
        { 177.16f, 29.32f }, { 179.34f, 28.6f }, { 180.79f, 27.57f }, { 182, 26 }, { 182.85f, 23.94f }, { 183.07f, 21.99f },
        { 182.7f, 19.76f }, { 181, 16 }, { 180.67f, 15.12f }, { 180.89f, 13.64f }, { 181.7f, 12.48f }, { 186, 9 },
        { 191.31f, 5.43f }, { 192.93f, 3.78f }, { 193.69f, 2.22f }, { 194, 0 }, { 193.67f, -2.29f }, { 192.85f, -3.9f },
        { 191.2f, -5.52f }, { 186, -9 }, { 181.62f, -12.57f }, { 180.84f, -13.73f }, { 180.64f, -14.53f }, { 181, -16 },
        { 182.74f, -19.88f }, { 183.07f, -22.12f }, { 182.82f, -24.07f }, { 182, -26 }, { 180.67f, -27.67f }, { 179.2f, -28.67f },
        { 177, -29.35f }, { 170, -29.5f }, { 144.03f, -29.79f }, { 118.5f, -30.48f }, { 92.47f, -31.16f }, { 68.05f, -31.27f },
        { 45.02f, -30.58f }, { 22, -29 }, { 14.11f, -28.4f }, { 11.28f, -27.49f }, { 9, -26 }, { 7.29f, -25.01f },
        { 2.08f, -23.6f }, { 0.78f, -22.99f }, { 0, -21.5f, true } };
    inline constexpr HeadPt classical_slotted_posts[] = {
        { 60, -15.5f }, { 95.5f, -15.5f }, { 131, -15.5f }, { 131, 15.5f }, { 95.5f, 15.5f }, { 60, 15.5f } };
    inline constexpr HeadPt classical_slotted_buttons[] = {
        { 60, -41.5f }, { 95.5f, -41.5f }, { 131, -41.5f }, { 131, 41.5f }, { 95.5f, 41.5f }, { 60, 41.5f } };
    inline constexpr HeadPt classical_slotted_slot0[] = {
        { 42, -15.5f }, { 42.1f, -14.29f }, { 42.34f, -13.43f }, { 42.68f, -12.7f }, { 43.63f, -11.6f }, { 45.03f, -10.83f },
        { 45.96f, -10.59f }, { 47, -10.5f }, { 145, -10.5f }, { 146.08f, -10.6f }, { 147.02f, -10.84f }, { 147.8f, -11.21f },
        { 148.95f, -12.17f }, { 149.7f, -13.54f }, { 149.92f, -14.41f }, { 150, -15.5f }, { 149.9f, -16.71f }, { 149.66f, -17.57f },
        { 149.32f, -18.3f }, { 148.37f, -19.4f }, { 146.97f, -20.17f }, { 146.04f, -20.41f }, { 145, -20.5f }, { 47, -20.5f },
        { 45.92f, -20.4f }, { 44.98f, -20.16f }, { 44.2f, -19.79f }, { 43.05f, -18.83f }, { 42.3f, -17.46f }, { 42.08f, -16.59f } };
    inline constexpr HeadPt classical_slotted_slot1[] = {
        { 42, 15.5f }, { 42.1f, 16.71f }, { 42.34f, 17.57f }, { 42.68f, 18.3f }, { 43.63f, 19.4f }, { 45.03f, 20.17f },
        { 45.96f, 20.41f }, { 47, 20.5f }, { 145, 20.5f }, { 146.08f, 20.4f }, { 147.02f, 20.16f }, { 147.8f, 19.79f },
        { 148.95f, 18.83f }, { 149.7f, 17.46f }, { 149.92f, 16.59f }, { 150, 15.5f }, { 149.9f, 14.29f }, { 149.66f, 13.43f },
        { 149.32f, 12.7f }, { 148.37f, 11.6f }, { 146.97f, 10.83f }, { 146.04f, 10.59f }, { 145, 10.5f }, { 47, 10.5f },
        { 45.92f, 10.6f }, { 44.98f, 10.84f }, { 44.2f, 11.21f }, { 43.05f, 12.17f }, { 42.3f, 13.54f }, { 42.08f, 14.41f } };

    // gypsy_slotted
    //   Selmer-style slotted headstock: a little narrower, gently flared, with a rounded arch
    //   top rising to a soft point.
    inline constexpr HeadPt gypsy_slotted_outline[] = {
        { 0, 21.5f, true }, { 5.64f, 23.15f }, { 9, 25 }, { 11.91f, 26.52f }, { 15.3f, 27.24f }, { 24, 27.5f },
        { 48.44f, 29.06f }, { 72.95f, 29.53f }, { 98.71f, 29.28f }, { 125.49f, 29.05f }, { 150, 29.5f }, { 161.71f, 30.46f },
        { 167.23f, 30.22f }, { 172, 29 }, { 178.7f, 25.82f }, { 182.69f, 22.52f }, { 186, 18 }, { 191.11f, 9.15f },
        { 192.53f, 4.86f }, { 193, 0 }, { 192.48f, -5.1f }, { 191.02f, -9.35f }, { 186, -18 }, { 182.53f, -22.68f },
        { 178.52f, -25.93f }, { 172, -29 }, { 167.09f, -30.24f }, { 161.45f, -30.45f }, { 150, -29.5f }, { 124.69f, -29.05f },
        { 97.97f, -29.29f }, { 71.47f, -29.52f }, { 47.64f, -29.03f }, { 24, -27.5f }, { 15.21f, -27.23f }, { 11.74f, -26.45f },
        { 9, -25 }, { 7.2f, -24.18f }, { 1.88f, -23.28f }, { 0.73f, -22.83f }, { 0, -21.5f, true } };
    inline constexpr HeadPt gypsy_slotted_posts[] = {
        { 58, -15.5f }, { 93.5f, -15.5f }, { 129, -15.5f }, { 129, 15.5f }, { 93.5f, 15.5f }, { 58, 15.5f } };
    inline constexpr HeadPt gypsy_slotted_buttons[] = {
        { 58, -41.5f }, { 93.5f, -41.5f }, { 129, -41.5f }, { 129, 41.5f }, { 93.5f, 41.5f }, { 58, 41.5f } };
    inline constexpr HeadPt gypsy_slotted_slot0[] = {
        { 40, -15.5f }, { 40.1f, -14.29f }, { 40.34f, -13.43f }, { 40.68f, -12.7f }, { 41.63f, -11.6f }, { 43.03f, -10.83f },
        { 43.96f, -10.59f }, { 45, -10.5f }, { 143, -10.5f }, { 144.08f, -10.6f }, { 145.02f, -10.84f }, { 145.8f, -11.21f },
        { 146.95f, -12.17f }, { 147.7f, -13.54f }, { 147.92f, -14.41f }, { 148, -15.5f }, { 147.9f, -16.71f }, { 147.66f, -17.57f },
        { 147.32f, -18.3f }, { 146.37f, -19.4f }, { 144.97f, -20.17f }, { 144.04f, -20.41f }, { 143, -20.5f }, { 45, -20.5f },
        { 43.92f, -20.4f }, { 42.98f, -20.16f }, { 42.2f, -19.79f }, { 41.05f, -18.83f }, { 40.3f, -17.46f }, { 40.08f, -16.59f } };
    inline constexpr HeadPt gypsy_slotted_slot1[] = {
        { 40, 15.5f }, { 40.1f, 16.71f }, { 40.34f, 17.57f }, { 40.68f, 18.3f }, { 41.63f, 19.4f }, { 43.03f, 20.17f },
        { 43.96f, 20.41f }, { 45, 20.5f }, { 143, 20.5f }, { 144.08f, 20.4f }, { 145.02f, 20.16f }, { 145.8f, 19.79f },
        { 146.95f, 18.83f }, { 147.7f, 17.46f }, { 147.92f, 16.59f }, { 148, 15.5f }, { 147.9f, 14.29f }, { 147.66f, 13.43f },
        { 147.32f, 12.7f }, { 146.37f, 11.6f }, { 144.97f, 10.83f }, { 144.04f, 10.59f }, { 143, 10.5f }, { 45, 10.5f },
        { 43.92f, 10.6f }, { 42.98f, 10.84f }, { 42.2f, 11.21f }, { 41.05f, 12.17f }, { 40.3f, 13.54f }, { 40.08f, 14.41f } };

    // resonator_slotted
    //   Resonator slotted headstock: square shoulders, straight sides and a flat top with
    //   rounded corners.
    inline constexpr HeadPt resonator_slotted_outline[] = {
        { 0, 21.5f, true }, { 2.91f, 22.54f }, { 5.68f, 24.42f }, { 8, 27 }, { 9.61f, 28.69f }, { 11.67f, 29.81f },
        { 18, 31 }, { 41.23f, 33.54f }, { 64.52f, 34.61f }, { 89.29f, 34.35f }, { 115.72f, 33.16f }, { 142.62f, 31.96f },
        { 168, 31.5f }, { 174.88f, 31.56f }, { 177.07f, 30.9f }, { 178.57f, 29.86f }, { 180, 28 }, { 182.05f, 23.6f },
        { 182.87f, 19.94f }, { 183, 12 }, { 183, -12 }, { 182.85f, -20.12f }, { 182.01f, -23.69f }, { 180, -28 },
        { 178.44f, -29.97f }, { 176.93f, -30.97f }, { 174.8f, -31.57f }, { 168, -31.5f }, { 141.66f, -31.99f }, { 114.83f, -33.21f },
        { 88.42f, -34.38f }, { 63.62f, -34.59f }, { 40.26f, -33.46f }, { 18, -31 }, { 11.55f, -29.77f }, { 9.5f, -28.61f },
        { 8, -27 }, { 6.94f, -25.93f }, { 4.2f, -24.57f }, { 0.91f, -23.13f }, { 0.34f, -22.57f }, { 0, -21.5f, true } };
    inline constexpr HeadPt resonator_slotted_posts[] = {
        { 62, -16 }, { 97.5f, -16 }, { 133, -16 }, { 133, 16 }, { 97.5f, 16 }, { 62, 16 } };
    inline constexpr HeadPt resonator_slotted_buttons[] = {
        { 62, -43 }, { 97.5f, -43 }, { 133, -43 }, { 133, 43 }, { 97.5f, 43 }, { 62, 43 } };
    inline constexpr HeadPt resonator_slotted_slot0[] = {
        { 44, -16 }, { 44.1f, -14.79f }, { 44.34f, -13.93f }, { 44.68f, -13.2f }, { 45.63f, -12.1f }, { 47.03f, -11.33f },
        { 47.96f, -11.09f }, { 49, -11 }, { 147, -11 }, { 148.08f, -11.1f }, { 149.02f, -11.34f }, { 149.8f, -11.71f },
        { 150.95f, -12.67f }, { 151.7f, -14.04f }, { 151.92f, -14.91f }, { 152, -16 }, { 151.9f, -17.21f }, { 151.66f, -18.07f },
        { 151.32f, -18.8f }, { 150.37f, -19.9f }, { 148.97f, -20.67f }, { 148.04f, -20.91f }, { 147, -21 }, { 49, -21 },
        { 47.92f, -20.9f }, { 46.98f, -20.66f }, { 46.2f, -20.29f }, { 45.05f, -19.33f }, { 44.3f, -17.96f }, { 44.08f, -17.09f } };
    inline constexpr HeadPt resonator_slotted_slot1[] = {
        { 44, 16 }, { 44.1f, 17.21f }, { 44.34f, 18.07f }, { 44.68f, 18.8f }, { 45.63f, 19.9f }, { 47.03f, 20.67f },
        { 47.96f, 20.91f }, { 49, 21 }, { 147, 21 }, { 148.08f, 20.9f }, { 149.02f, 20.66f }, { 149.8f, 20.29f },
        { 150.95f, 19.33f }, { 151.7f, 17.96f }, { 151.92f, 17.09f }, { 152, 16 }, { 151.9f, 14.79f }, { 151.66f, 13.93f },
        { 151.32f, 13.2f }, { 150.37f, 12.1f }, { 148.97f, 11.33f }, { 148.04f, 11.09f }, { 147, 11 }, { 49, 11 },
        { 47.92f, 11.1f }, { 46.98f, 11.34f }, { 46.2f, 11.71f }, { 45.05f, 12.67f }, { 44.3f, 14.04f }, { 44.08f, 14.91f } };

    // bass_inline4
    //   Fender-style bass headstock: the Strat geometry scaled up - straight bass edge slanting
    //   toward the treble side so the strings pull straight, big keys, S-curved treble edge
    //   and a round bulb; ~230 mm long for a 38 mm nut.
    inline constexpr HeadPt bass_inline4_outline[] = {
        { 0, 19, true }, { 16.1f, 20.63f }, { 26, 23.5f }, { 40.14f, 29.8f }, { 50, 36 }, { 58.59f, 41.42f },
        { 64.09f, 43.37f }, { 70, 44 }, { 82.44f, 43.41f }, { 94.8f, 41.61f }, { 112, 38 }, { 130.77f, 34.53f },
        { 152, 31.5f }, { 162, 31.2f }, { 163.67f, 31.59f }, { 165.43f, 32.56f }, { 167.82f, 34.79f }, { 172, 41 },
        { 174.28f, 44.02f }, { 177.32f, 46.41f }, { 186, 50.5f }, { 191.65f, 52.4f }, { 200, 53 }, { 210.11f, 52.31f },
        { 214.48f, 50.68f }, { 218, 48 }, { 222.22f, 42.88f }, { 224.51f, 38.24f }, { 226, 32 }, { 225.98f, 27.14f },
        { 223, 18 }, { 221.44f, 15.02f }, { 219.04f, 12.45f }, { 212, 8, true }, { 46, -34 }, { 37.09f, -36.11f },
        { 32, -36.5f }, { 26.72f, -35.99f }, { 23.22f, -34.79f }, { 20.49f, -33.06f }, { 18, -30.5f }, { 16.17f, -28.74f },
        { 11.92f, -26.49f }, { 8.28f, -24.5f }, { 6.87f, -23.07f }, { 6, -21.5f }, { 5.22f, -20.65f }, { 4.15f, -20.29f },
        { 0.92f, -19.92f }, { 0, -19, true } };
    inline constexpr HeadPt bass_inline4_posts[] = {
        { 52, -15.5f }, { 98, -5.5f }, { 144, 4.5f }, { 190, 14.5f } };
    inline constexpr HeadPt bass_inline4_buttons[] = {
        { 60.83f, -50.4f }, { 106.83f, -40.4f }, { 152.83f, -30.4f }, { 198.83f, -20.4f } };

    // bass_inline5
    //   Five-string version: longer, the same straight-pull geometry.
    inline constexpr HeadPt bass_inline5_outline[] = {
        { 0, 19, true }, { 16.1f, 20.63f }, { 26, 23.5f }, { 42.09f, 30.39f }, { 52, 36.5f }, { 60.42f, 41.63f },
        { 66.83f, 43.79f }, { 74, 44.5f }, { 90.31f, 43.88f }, { 105.89f, 41.99f }, { 125, 38.5f }, { 141.73f, 35.81f },
        { 161.5f, 33.68f }, { 180, 31.5f }, { 185.61f, 31.03f }, { 191, 31.2f }, { 192.89f, 31.64f }, { 195.04f, 32.82f },
        { 197.79f, 35.38f }, { 202, 41.5f }, { 204.35f, 44.53f }, { 207.62f, 46.92f }, { 217, 51 }, { 222.79f, 52.92f },
        { 232, 53.5f }, { 242.91f, 52.86f }, { 247.39f, 51.23f }, { 251, 48.5f }, { 256.19f, 42.36f }, { 258.61f, 37.62f },
        { 260, 32 }, { 259.98f, 27.14f }, { 257, 18 }, { 256.04f, 16.14f }, { 254.69f, 14.63f }, { 252.31f, 13.03f },
        { 246, 10, true }, { 46, -35 }, { 36.92f, -37.11f }, { 32, -37.5f }, { 27.17f, -36.99f }, { 23.72f, -35.78f },
        { 20.81f, -33.9f }, { 18, -31 }, { 15.5f, -28.71f }, { 9.34f, -25.37f }, { 7.17f, -23.49f }, { 6, -21.5f },
        { 5.22f, -20.65f }, { 4.15f, -20.29f }, { 0.92f, -19.92f }, { 0, -19, true } };
    inline constexpr HeadPt bass_inline5_posts[] = {
        { 50, -16.5f }, { 93, -8.38f }, { 136, -0.25f }, { 179, 7.88f }, { 222, 16 } };
    inline constexpr HeadPt bass_inline5_buttons[] = {
        { 57.9f, -51.62f }, { 100.9f, -43.5f }, { 143.9f, -35.37f }, { 186.9f, -27.25f }, { 229.9f, -19.12f } };

    // bass_22
    //   2+2 bass headstock for hollow and violin basses: flared sides, rounded shoulders at
    //   the top and a gently domed top edge.
    inline constexpr HeadPt bass_22_outline[] = {
        { 0, 19, true }, { 7.79f, 20.46f }, { 11.36f, 21.83f }, { 14, 23.5f }, { 21.57f, 28.22f }, { 34, 32.5f },
        { 52.43f, 36.51f }, { 71.49f, 38.14f }, { 96.12f, 38.12f }, { 120, 38.5f }, { 135.34f, 40.25f }, { 142.84f, 39.86f },
        { 150, 37.5f }, { 154.19f, 34.95f }, { 156.74f, 32.32f }, { 158.56f, 29.13f }, { 160, 24 }, { 163.11f, 10.81f },
        { 164, 0 }, { 163.08f, -10.95f }, { 160, -24 }, { 158.48f, -29.32f }, { 156.62f, -32.48f }, { 154.02f, -35.09f },
        { 150, -37.5f }, { 142.65f, -39.89f }, { 134.99f, -40.22f }, { 120, -38.5f }, { 95.59f, -38.12f }, { 70.48f, -38.1f },
        { 51.36f, -36.34f }, { 34, -32.5f }, { 21.45f, -28.17f }, { 14, -23.5f }, { 12.03f, -22.46f }, { 7.87f, -21.74f },
        { 1.87f, -21.18f }, { 0.8f, -20.68f }, { 0, -19, true } };
    inline constexpr HeadPt bass_22_posts[] = {
        { 60, -24 }, { 110, -26.5f }, { 110, 26.5f }, { 60, 24 } };
    inline constexpr HeadPt bass_22_buttons[] = {
        { 60, -56 }, { 110, -58.5f }, { 110, 58.5f }, { 60, 56 } };
    inline constexpr HeadPt bass_22_truss[] = {
        { 6, -4.5f }, { 6, 4.5f }, { 8.29f, 5.16f }, { 11.05f, 5.62f }, { 15.43f, 6.02f }, { 19.79f, 6.45f },
        { 23.1f, 7.02f }, { 25.8f, 7.75f }, { 29.39f, 9.05f }, { 32.46f, 10.13f }, { 34.68f, 10.68f }, { 37, 11 },
        { 38.01f, 11 }, { 39.25f, 10.66f }, { 40.16f, 10 }, { 40.94f, 8.85f }, { 41.33f, 7.85f }, { 41.67f, 6.34f },
        { 41.93f, 3.82f }, { 42, 0 }, { 41.92f, -3.92f }, { 41.66f, -6.19f }, { 41.28f, -7.68f }, { 40.87f, -8.62f },
        { 40.42f, -9.32f }, { 39.43f, -10.24f }, { 38.01f, -10.84f }, { 37, -11 }, { 35.13f, -11.02f }, { 33.53f, -10.78f },
        { 31.75f, -10.24f }, { 28.47f, -8.8f }, { 25.8f, -7.75f }, { 22.83f, -6.96f }, { 19.66f, -6.43f }, { 15.3f, -6.01f },
        { 10.93f, -5.61f }, { 8.07f, -5.11f } };

    // bass_31
    //   3+1 bass headstock: three keys along the bass side, the G key alone on the treble side
    //   near the nut; a rounded, asymmetric outline that is widest at the treble key.
    inline constexpr HeadPt bass_31_outline[] = {
        { 0, 19, true }, { 10.57f, 21.21f }, { 16, 24 }, { 24.41f, 28.48f }, { 40, 33.5f }, { 49.98f, 36.54f },
        { 58.83f, 38.02f }, { 70, 38.5f }, { 83.82f, 38.08f }, { 92.89f, 36.7f }, { 102, 34 }, { 115.53f, 30.18f },
        { 134.13f, 27.22f }, { 150, 24 }, { 164.83f, 20.54f }, { 171.11f, 17.83f }, { 176, 14 }, { 181.26f, 8.02f },
        { 183.04f, 4.63f }, { 183.96f, 0.89f }, { 184, -4 }, { 182.24f, -15.05f }, { 179.99f, -19.7f }, { 176, -24 },
        { 167.28f, -30.1f }, { 159.61f, -33.28f }, { 150, -35 }, { 130.97f, -36.21f }, { 111.6f, -36.55f }, { 90, -36.5f },
        { 70.17f, -36.41f }, { 54.87f, -35.55f }, { 40, -33.5f }, { 28.55f, -31.05f }, { 22.04f, -28.57f }, { 16, -25 },
        { 13.42f, -23.76f }, { 6.26f, -22.55f }, { 2, -21.69f }, { 0.96f, -21.09f }, { 0, -19, true } };
    inline constexpr HeadPt bass_31_posts[] = {
        { 56, -23.5f }, { 100, -25 }, { 144, -24 }, { 72, 24.5f } };
    inline constexpr HeadPt bass_31_buttons[] = {
        { 56, -57 }, { 100, -59 }, { 144, -58 }, { 72, 57 } };

    // headless
    //   Headless guitar: a short end cap carrying the string anchors (tuners are at the bridge).
    inline constexpr HeadPt headless_outline[] = {
        { 0, 21.5f, true }, { 5.93f, 22.31f }, { 12, 23 }, { 12.97f, 22.85f }, { 13.72f, 22.49f }, { 14.47f, 21.81f },
        { 15.24f, 20.57f }, { 16, 18 }, { 17.06f, 8.2f }, { 16.71f, -3.4f }, { 16, -18 }, { 15.69f, -19.95f },
        { 14.94f, -21.43f }, { 14.04f, -22.33f }, { 13.03f, -22.84f }, { 12, -23 }, { 3.48f, -23.62f }, { 1.41f, -23.33f },
        { 0.67f, -22.95f }, { 0, -21.5f, true } };
    inline constexpr HeadPt headless_posts[] = {
        { 9, -18 }, { 9, -10.8f }, { 9, -3.6f }, { 9, 3.6f }, { 9, 10.8f }, { 9, 18 } };

    // headless_bass
    //   Headless bass: the end cap sized for four strings on a 38 mm nut.
    inline constexpr HeadPt headless_bass_outline[] = {
        { 0, 19, true }, { 6.43f, 20.07f }, { 13, 21 }, { 14.33f, 20.81f }, { 15.45f, 20.28f }, { 16.48f, 19.37f },
        { 17.39f, 17.96f }, { 18, 16 }, { 18.96f, 3.16f }, { 18, -16 }, { 17.74f, -17.61f }, { 17.01f, -18.98f },
        { 15.92f, -20.05f }, { 14.51f, -20.77f }, { 13, -21 }, { 3.77f, -21.46f }, { 1.59f, -21.08f }, { 0.77f, -20.65f },
        { 0, -19, true } };
    inline constexpr HeadPt headless_bass_posts[] = {
        { 10, -14.5f }, { 10, -4.83f }, { 10, 4.84f }, { 10, 14.51f } };

    template <typename T, int N> constexpr int count (const T (&)[N]) { return N; }
}

//==============================================================================
inline constexpr HeadstockStyle kHeadstockStyles[] = {
    { "strat_inline6", HeadLayout::inline6,
      headstock_data::strat_inline6_outline, headstock_data::count (headstock_data::strat_inline6_outline),
      headstock_data::strat_inline6_posts, 6,
      headstock_data::strat_inline6_buttons, 6, 16, 11,
      nullptr, 0,
      { nullptr, nullptr }, { 0, 0 },
      { 96, 12.5f }, true },
    { "tele_inline6", HeadLayout::inline6,
      headstock_data::tele_inline6_outline, headstock_data::count (headstock_data::tele_inline6_outline),
      headstock_data::tele_inline6_posts, 6,
      headstock_data::tele_inline6_buttons, 6, 16, 11,
      nullptr, 0,
      { nullptr, nullptr }, { 0, 0 },
      { 98, 12 }, true },
    { "offset_inline6", HeadLayout::inline6,
      headstock_data::offset_inline6_outline, headstock_data::count (headstock_data::offset_inline6_outline),
      headstock_data::offset_inline6_posts, 6,
      headstock_data::offset_inline6_buttons, 6, 16, 11,
      nullptr, 0,
      { nullptr, nullptr }, { 0, 0 },
      { 98, 12.5f }, true },
    { "superstrat_inline6", HeadLayout::inline6,
      headstock_data::superstrat_inline6_outline, headstock_data::count (headstock_data::superstrat_inline6_outline),
      headstock_data::superstrat_inline6_posts, 6,
      headstock_data::superstrat_inline6_buttons, 6, 14, 10,
      nullptr, 0,
      { nullptr, nullptr }, { 0, 0 },
      { 0, 0 }, false },
    { "reverse_inline6", HeadLayout::inlineReverse,
      headstock_data::reverse_inline6_outline, headstock_data::count (headstock_data::reverse_inline6_outline),
      headstock_data::reverse_inline6_posts, 6,
      headstock_data::reverse_inline6_buttons, 6, 14, 10,
      nullptr, 0,
      { nullptr, nullptr }, { 0, 0 },
      { 0, 0 }, false },
    { "inline7", HeadLayout::inline6,
      headstock_data::inline7_outline, headstock_data::count (headstock_data::inline7_outline),
      headstock_data::inline7_posts, 7,
      headstock_data::inline7_buttons, 7, 14, 10,
      nullptr, 0,
      { nullptr, nullptr }, { 0, 0 },
      { 0, 0 }, false },
    { "inline8", HeadLayout::inline6,
      headstock_data::inline8_outline, headstock_data::count (headstock_data::inline8_outline),
      headstock_data::inline8_posts, 8,
      headstock_data::inline8_buttons, 8, 14, 10,
      nullptr, 0,
      { nullptr, nullptr }, { 0, 0 },
      { 0, 0 }, false },
    { "explorer_hockey", HeadLayout::inline6,
      headstock_data::explorer_hockey_outline, headstock_data::count (headstock_data::explorer_hockey_outline),
      headstock_data::explorer_hockey_posts, 6,
      headstock_data::explorer_hockey_buttons, 6, 15, 11,
      headstock_data::explorer_hockey_truss, headstock_data::count (headstock_data::explorer_hockey_truss),
      { nullptr, nullptr }, { 0, 0 },
      { 0, 0 }, false },
    { "firebird_inline6", HeadLayout::inline6,
      headstock_data::firebird_inline6_outline, headstock_data::count (headstock_data::firebird_inline6_outline),
      headstock_data::firebird_inline6_posts, 6,
      headstock_data::firebird_inline6_buttons, 6, 10, 8,
      nullptr, 0,
      { nullptr, nullptr }, { 0, 0 },
      { 0, 0 }, false },
    { "lp_33", HeadLayout::threeThree,
      headstock_data::lp_33_outline, headstock_data::count (headstock_data::lp_33_outline),
      headstock_data::lp_33_posts, 6,
      headstock_data::lp_33_buttons, 6, 16, 12,
      headstock_data::lp_33_truss, headstock_data::count (headstock_data::lp_33_truss),
      { nullptr, nullptr }, { 0, 0 },
      { 0, 0 }, false },
    { "sg_33", HeadLayout::threeThree,
      headstock_data::sg_33_outline, headstock_data::count (headstock_data::sg_33_outline),
      headstock_data::sg_33_posts, 6,
      headstock_data::sg_33_buttons, 6, 16, 12,
      headstock_data::sg_33_truss, headstock_data::count (headstock_data::sg_33_truss),
      { nullptr, nullptr }, { 0, 0 },
      { 0, 0 }, false },
    { "v_33", HeadLayout::threeThree,
      headstock_data::v_33_outline, headstock_data::count (headstock_data::v_33_outline),
      headstock_data::v_33_posts, 6,
      headstock_data::v_33_buttons, 6, 16, 12,
      headstock_data::v_33_truss, headstock_data::count (headstock_data::v_33_truss),
      { nullptr, nullptr }, { 0, 0 },
      { 0, 0 }, false },
    { "acoustic_33", HeadLayout::threeThree,
      headstock_data::acoustic_33_outline, headstock_data::count (headstock_data::acoustic_33_outline),
      headstock_data::acoustic_33_posts, 6,
      headstock_data::acoustic_33_buttons, 6, 15, 11,
      headstock_data::acoustic_33_truss, headstock_data::count (headstock_data::acoustic_33_truss),
      { nullptr, nullptr }, { 0, 0 },
      { 0, 0 }, false },
    { "archtop_33", HeadLayout::threeThree,
      headstock_data::archtop_33_outline, headstock_data::count (headstock_data::archtop_33_outline),
      headstock_data::archtop_33_posts, 6,
      headstock_data::archtop_33_buttons, 6, 17, 12,
      headstock_data::archtop_33_truss, headstock_data::count (headstock_data::archtop_33_truss),
      { nullptr, nullptr }, { 0, 0 },
      { 0, 0 }, false },
    { "twelve_66", HeadLayout::sixSix,
      headstock_data::twelve_66_outline, headstock_data::count (headstock_data::twelve_66_outline),
      headstock_data::twelve_66_posts, 12,
      headstock_data::twelve_66_buttons, 12, 13, 10,
      headstock_data::twelve_66_truss, headstock_data::count (headstock_data::twelve_66_truss),
      { nullptr, nullptr }, { 0, 0 },
      { 0, 0 }, false },
    { "classical_slotted", HeadLayout::slotted,
      headstock_data::classical_slotted_outline, headstock_data::count (headstock_data::classical_slotted_outline),
      headstock_data::classical_slotted_posts, 6,
      headstock_data::classical_slotted_buttons, 6, 14, 10,
      nullptr, 0,
      { headstock_data::classical_slotted_slot0, headstock_data::classical_slotted_slot1 }, { headstock_data::count (headstock_data::classical_slotted_slot0), headstock_data::count (headstock_data::classical_slotted_slot1) },
      { 0, 0 }, false },
    { "gypsy_slotted", HeadLayout::slotted,
      headstock_data::gypsy_slotted_outline, headstock_data::count (headstock_data::gypsy_slotted_outline),
      headstock_data::gypsy_slotted_posts, 6,
      headstock_data::gypsy_slotted_buttons, 6, 14, 10,
      nullptr, 0,
      { headstock_data::gypsy_slotted_slot0, headstock_data::gypsy_slotted_slot1 }, { headstock_data::count (headstock_data::gypsy_slotted_slot0), headstock_data::count (headstock_data::gypsy_slotted_slot1) },
      { 0, 0 }, false },
    { "resonator_slotted", HeadLayout::slotted,
      headstock_data::resonator_slotted_outline, headstock_data::count (headstock_data::resonator_slotted_outline),
      headstock_data::resonator_slotted_posts, 6,
      headstock_data::resonator_slotted_buttons, 6, 14, 10,
      nullptr, 0,
      { headstock_data::resonator_slotted_slot0, headstock_data::resonator_slotted_slot1 }, { headstock_data::count (headstock_data::resonator_slotted_slot0), headstock_data::count (headstock_data::resonator_slotted_slot1) },
      { 0, 0 }, false },
    { "bass_inline4", HeadLayout::fourInline,
      headstock_data::bass_inline4_outline, headstock_data::count (headstock_data::bass_inline4_outline),
      headstock_data::bass_inline4_posts, 4,
      headstock_data::bass_inline4_buttons, 4, 22, 18,
      nullptr, 0,
      { nullptr, nullptr }, { 0, 0 },
      { 118, 10 }, true },
    { "bass_inline5", HeadLayout::fourInline,
      headstock_data::bass_inline5_outline, headstock_data::count (headstock_data::bass_inline5_outline),
      headstock_data::bass_inline5_posts, 5,
      headstock_data::bass_inline5_buttons, 5, 22, 18,
      nullptr, 0,
      { nullptr, nullptr }, { 0, 0 },
      { 154, 12 }, true },
    { "bass_22", HeadLayout::twoTwo,
      headstock_data::bass_22_outline, headstock_data::count (headstock_data::bass_22_outline),
      headstock_data::bass_22_posts, 4,
      headstock_data::bass_22_buttons, 4, 22, 18,
      headstock_data::bass_22_truss, headstock_data::count (headstock_data::bass_22_truss),
      { nullptr, nullptr }, { 0, 0 },
      { 0, 0 }, false },
    { "bass_31", HeadLayout::threeOne,
      headstock_data::bass_31_outline, headstock_data::count (headstock_data::bass_31_outline),
      headstock_data::bass_31_posts, 4,
      headstock_data::bass_31_buttons, 4, 22, 18,
      nullptr, 0,
      { nullptr, nullptr }, { 0, 0 },
      { 0, 0 }, false },
    { "headless", HeadLayout::headless,
      headstock_data::headless_outline, headstock_data::count (headstock_data::headless_outline),
      headstock_data::headless_posts, 6,
      nullptr, 0, 0, 0,
      nullptr, 0,
      { nullptr, nullptr }, { 0, 0 },
      { 0, 0 }, false },
    { "headless_bass", HeadLayout::headless,
      headstock_data::headless_bass_outline, headstock_data::count (headstock_data::headless_bass_outline),
      headstock_data::headless_bass_posts, 4,
      nullptr, 0, 0, 0,
      nullptr, 0,
      { nullptr, nullptr }, { 0, 0 },
      { 0, 0 }, false },
};

inline constexpr int kNumHeadstockStyles = (int) (sizeof (kHeadstockStyles) / sizeof (kHeadstockStyles[0]));

/** The headstock with this id, or nullptr if there is none. */
inline const HeadstockStyle* findHeadstockStyle (const char* id) noexcept
{
    if (id == nullptr)
        return nullptr;

    for (int i = 0; i < kNumHeadstockStyles; ++i)
        if (std::strcmp (kHeadstockStyles[i].id, id) == 0)
            return &kHeadstockStyles[i];

    return nullptr;
}

/** The headstock a body style carries by default (guitar-illustration.md 6). Never null. */
inline const char* defaultHeadstockFor (const char* bodyStyleId, int numStrings) noexcept
{
    auto is = [bodyStyleId] (const char* s) { return bodyStyleId != nullptr && std::strcmp (bodyStyleId, s) == 0; };
    auto startsWith = [bodyStyleId] (const char* s) { return bodyStyleId != nullptr && std::strncmp (bodyStyleId, s, std::strlen (s)) == 0; };

    if (numStrings >= 12)                                             return "twelve_66";
    if (is ("headless_bass"))                                         return "headless_bass";

    if (startsWith ("bass") || is ("acoustic_bass"))
    {
        if (is ("bass_hollow") || is ("bass_violin") || is ("acoustic_bass"))  return "bass_22";
        if (is ("bass_musicman"))                                    return "bass_31";
        return numStrings >= 5 ? "bass_inline5" : "bass_inline4";
    }

    if (numStrings == 7)                                             return "inline7";
    if (numStrings >= 8)                                             return "inline8";

    if (is ("double_cutaway_offset"))                                return "strat_inline6";
    if (is ("offset"))                                               return "offset_inline6";
    if (is ("reverse_firebird"))                                     return "firebird_inline6";
    if (is ("single_cutaway_slab"))                                  return "tele_inline6";
    if (is ("superstrat") || is ("multiscale"))                      return "superstrat_inline6";
    if (is ("angular"))                                              return "explorer_hockey";
    if (is ("flying_v"))                                             return "v_33";
    if (is ("double_cutaway_thin"))                                  return "sg_33";
    if (is ("archtop"))                                              return "archtop_33";
    if (is ("single_cutaway_arched") || is ("double_cutaway_semi"))  return "lp_33";
    if (startsWith ("gypsy_jazz"))                                   return "gypsy_slotted";
    if (is ("classical") || is ("flamenco") || is ("cutaway_classical"))  return "classical_slotted";
    if (startsWith ("resonator"))                                    return "resonator_slotted";

    return "acoustic_33";
}

} // namespace luthier::outlines
